# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名人')),
                ('cover', models.ImageField(default=None, upload_to='static/image/post', verbose_name='图片')),
            ],
            options={
                'verbose_name': '名人',
                'verbose_name_plural': '名人',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default=None, upload_to='static/image/post', verbose_name='图片')),
            ],
            options={
                'verbose_name': '影集',
                'verbose_name_plural': '影集',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.CharField(max_length=4000, verbose_name='内容')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('cover', models.ImageField(default=None, upload_to='static/image/post', verbose_name='作品封面')),
                ('views', models.IntegerField(verbose_name='浏览量')),
                ('is_recomment', models.BooleanField(default=False, verbose_name='是否推荐作品')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '作品分类',
                'verbose_name_plural': '作品分类',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Boke_app.Works', verbose_name='作品分类'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='Boke_app.Tags', verbose_name='标签'),
        ),
    ]
