# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boke_app', '0002_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enjoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default=None, upload_to='static/image/post', verbose_name='作品')),
                ('title', models.CharField(max_length=30, verbose_name='作品名称')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boke_app.Post', verbose_name='作品介绍')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
    ]
